name: hotio-nzbget
services:
  nzbget:
    container_name: nzbget
    image: ghcr.io/hotio/nzbget:release
    ports:
      - target: 6789
        published: "6789"
        protocol: tcp
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - UMASK=002
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
      - type: bind
        source: /DATA/Media
        target: /data/Media
    restart: unless-stopped
    x-casaos:
      envs:
        - container: PUID
          label:
            en_US: "User ID"
          description:
            en_US: "The user ID for the container (recommended: 1000)."
          default: "1000"
        - container: PGID
          label:
            en_US: "Group ID"
          description:
            en_US: "The group ID for the container (recommended: 1000)."
          default: "1000"
        - container: TZ
          label:
            en_US: "Timezone"
          description:
            en_US: "Set the timezone for the container."
          default: "America/Los_Angeles"
      ports:
        - container: "6789"
          description:
            en_US: "The internal port for NZB download client."
      volumes:
        - container: /config
          description:
            en_US: "The persistent directory for NZB download client configuration."
        - container: /data/Media
          description:
            en_US: "The persistent directory for Media Library server configuration."

x-casaos:
  architectures:
    - amd64
    - arm64
    - arm
  main: nzbget
  category: Hotio
  developer: Hotio
  author: Homelab-Appstore
  tagline:
    en_US: "NZB download client"
  description:
    en_US: |
      ğŸ“¥ NZBGet is a binary newsgrabber for nzb files, written in C++.

      It supports downloading from Usenet servers, with features like queue management, post-processing scripts, and web interface.

      Efficient and lightweight, it's a popular choice for automating Usenet downloads in media management stacks.

      **Please use the provided pathing in the before install popup, or when clicking tips on the app in the app list.**
      These containers are setup for consistensy with the servarr [**folder**](https://wiki.servarr.com/en/docker-guide#consistent-and-well-planned-paths) setup

      âš™ï¸ğŸ“ºğŸµ Official wiki for the Servarr suite of applications. ğŸµğŸ“ºâš™ï¸
      Find best practices and comprehensive configuration guides,
      including essential Docker setup for your automated media center.
      â¡ï¸ ğŸ“ºğŸµ[**Servarr**](https://wiki.servarr.com/)ğŸµğŸ“º

      â¡ï¸ ğŸ”¥ [**hotio.dev**](https://hotio.dev/) ğŸ”¥

      â¡ï¸ [**GitHub Repo**](https://github.com/acidgreenservers/CasaOS-Hotio-Appstore)

      If you want to create more folders in the Media folder, you may have to run "chmod folder-name 755" on the host machine as root
      in order to give the folder proper permissions for these apps

      **Click The Tips Button On The App Icon in The Apps List For More Info if You Custom Installed**

  icon: "https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/nzbget.png"
  thumbnail: ""
  screenshot_link: []
  port_map: "6789"
  scheme: http
  title:
    en_US: "Hotio nzbget"
  tips:
    before_install:
      en_us: |
        | Name | Value |
        | ---- | ----- |
        | Movies Path To Set Inside Container | `/DATA/Media/Movies` |
        | TV Shows Path To Set Inside Container | `/DATA/Media/TV Shows` |
        | Music Path To Set Inside Container | `/DATA/Media/Music` |

        This pathing setup is consistent with Servarr best practice
        when it comes to naming folders. 
        this will allow hardlinking
        and other features you want, while keeping the paths also
        consistent with CasaOS.

        Please make sure to set the paths correctly inside the container
        after it is running, before beginning to use the app for production.

        Permissions are setup correctly across folders for
        hotio apps as per servarr 
        
        Just set the folder paths shown inside the containers.
