name: hotio-prowlarr
services:
  prowlarr:
    container_name: prowlarr
    image: ghcr.io/hotio/prowlarr:release
    ports:
      - target: 9696
        published: "9696"
        protocol: tcp
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - UMASK=002
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    restart: unless-stopped
    x-casaos:
      envs:
        - container: PUID
          label:
            en_US: "User ID"
          description:
            en_US: "The user ID for the container (recommended: 1000)."
          default: "1000"
        - container: PGID
          label:
            en_US: "Group ID"
          description:
            en_US: "The group ID for the container (recommended: 1000)."
          default: "1000"
        - container: TZ
          label:
            en_US: "Timezone"
          description:
            en_US: "Set the timezone for the container."
          default: "America/Los_Angeles"
      ports:
        - container: "9696"
          description:
            en_US: "The internal port for Indexer management."
      volumes:
        - container: /config
          description:
            en_US: "The persistent directory for Indexer management configuration."

x-casaos:
  architectures:
    - amd64
    - arm64
    - arm
  main: prowlarr
  category: Hotio
  developer: Hotio
  author: Homelab-Appstore
  tagline:
    en_US: "Indexer management"
  description:
    en_US: |
      ğŸ” Prowlarr is an indexer manager and proxy for Usenet and Torrent users.

      It integrates with applications like Sonarr and Radarr to automatically add and manage indexers, providing a centralized way to handle your indexer sources.

      With support for Torznab and Newznab, Prowlarr simplifies indexer configuration and maintenance.

      âš™ï¸ğŸ“ºğŸµ Official wiki for the Servarr suite of applications. ğŸµğŸ“ºâš™ï¸
      Find best practices and comprehensive configuration guides,
      including essential Docker setup for your automated media center.
      â¡ï¸ ğŸ“ºğŸµ[**Servarr**](https://wiki.servarr.com/)ğŸµğŸ“º

      â¡ï¸ ğŸ”¥ [**hotio.dev**](https://hotio.dev/) ğŸ”¥

      â¡ï¸ [**GitHub Repo**](https://github.com/acidgreenservers/CasaOS-Hotio-Appstore)

      If you want to create more folders in the Media folder, you may have to run "chmod folder-name 755" on the host machine as root
      in order to give the folder proper permissions for these apps

      **Click The Tips Button On The App Icon in The Apps List For More Info if You Custom Installed**

  icon: "https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/prowlarr.png"
  thumbnail: ""
  screenshot_link: []
  port_map: "9696"
  scheme: http
  title:
    en_US: "Hotio Prowlarr"
  tips: {}